# Use a minimal Node.js LTS image
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY BackEnd/index.js ./
COPY BackEnd/db.js ./
COPY BackEnd/src ./src
COPY BackEnd/node_modules ./node_modules

# Start the server
CMD ["node", "index.js"]