---
- name: Build and Run Backend on Remote Hosts
  hosts: backend
  become: yes

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes
        
    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Ensure backend container is absent
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Remove existing backend image
      shell: docker rmi {{ backend_image }} || true
      ignore_errors: yes

    - name: Pull Backend Docker image
      docker_image:
        name: "{{ backend_image }}"
        source: pull

    - name: Stop any process using port {{ backend_port }}
      shell: |
        lsof -i :{{ backend_port }} -t | xargs -r sudo kill -9
      ignore_errors: yes

    - name: Run Backend container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ backend_image }}"
        ports:
          - "{{ backend_port }}:{{ backend_port }}"
        restart_policy: always
        state: started
        env:
          PORT: "{{ backend_port }}"
          DB_USER_NAME: "{{ DB_USER_NAME }}"
          DB_PASSWORD: "{{ DB_PASSWORD }}"
          DB_NAME: "{{ DB_NAME }}"
          DB_URI: "{{ DB_URI }}"
          HASHING_COST: "10"
          ENCRYPTION_KEY: "{{ ENCRYPTION_KEY }}"

    - name: Verify container is running
      shell: docker ps --filter "name={{ container_name }}"
      register: container_status
      changed_when: false

    - name: Show container status
      debug:
        var: container_status.stdout_lines

    - name: Check container logs for errors
      shell: docker logs {{ container_name }}
      register: container_logs
      changed_when: false
      ignore_errors: yes

    - name: Display container logs
      debug:
        var: container_logs.stdout_lines